import type { Metadata } from 'next'
import Link from 'next/link'
import { ThemeToggle } from '@/components/theme-toggle'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <div className="min-h-full flex flex-col">
      <main className="w-full max-w-3xl mx-auto px-5 sm:px-20">
        <header className="flex items-center justify-between w-full h-20">
          <Link href="/">
            <span className="tracking-widest leading-5 text-xs text-zinc-500 hover:text-zinc-950 dark:hover:text-white font-bold">
              UNDER
            </span>
          </Link>

          <nav className="flex items-center gap-5">
            <ThemeToggle />
          </nav>
        </header>
        {children}
      </main>
    </div>
  )
}
